postgres:
    image: postgres:9.6-alpine
    ports:
      - '10042:5432'
    environment:
      POSTGRES_USER: 'imagecurl'
      POSTGRES_PASSWORD: 'salasana12'
      POSTGRES_DB: 'imagecurl'

# docker-compose -f docker-compose.yml up
